### ISSUE TITLE
好像如果有子文件夹的话 不会处理？

### ISSUE THREAD

**Issue by wangdenkun** [mjl0602/flutter-assets-maker#1]
顺便提一下 npm install之后可能会有cannot run in wd sharp@0.22.1的问题
换成 npm install --unsafe-perm 就好了
感谢作者 save my day Thanks♪(･ω･)ﾉ

**Comment by mjl0602** [comment]
这个是想过的，考虑到一般项目的资源其实并不多（很难上百个），而且还要递归搞，好麻烦啊，而且递归之后怎么处理资源也是一个问题。所以暂时不会有增加递归的计划。只能建议用命名的形式管理资源了。
